/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projexct1;

/**
 *
 * @author Zelone
 */
public class Item extends javax.swing.JFrame {

    /**
     * Creates new form Item
     */
    public Item() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ItemNameLabel = new javax.swing.JLabel();
        ItemPriceLbel = new javax.swing.JLabel();
        ItemDetailsImageLabel = new javax.swing.JLabel();
        ItemLogoImageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        ItemNameLabel.setText("jLabel1");
        getContentPane().add(ItemNameLabel);
        ItemNameLabel.setBounds(117, 6, 480, 55);

        ItemPriceLbel.setText("jLabel1");
        getContentPane().add(ItemPriceLbel);
        ItemPriceLbel.setBounds(0, 150, 577, 127);

        ItemDetailsImageLabel.setText("jLabel1");
        getContentPane().add(ItemDetailsImageLabel);
        ItemDetailsImageLabel.setBounds(0, 0, 620, 260);

        ItemLogoImageLabel.setText("jLabel1");
        getContentPane().add(ItemLogoImageLabel);
        ItemLogoImageLabel.setBounds(7, 0, 90, 60);

        setSize(new java.awt.Dimension(632, 295));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Item().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ItemDetailsImageLabel;
    private javax.swing.JLabel ItemLogoImageLabel;
    private javax.swing.JLabel ItemNameLabel;
    private javax.swing.JLabel ItemPriceLbel;
    // End of variables declaration//GEN-END:variables
}
